version: '4.0'

services:
  database:
    image: 'postgres:alpine'
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: taxi24
  
  server:
    build: .
    ports:
      - '${PORT}:3000'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}