version: '4.0'

services:
  database:
    image: 'postgres:alpine'
    ports:
      - '${DB_PORT}:5000'
    environment:
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'
  
  server:
    build: .
    ports:
      - '${PORT}:3000'
    environment:
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'